package(default_visibility = ["//visibility:public"])

licenses(["notice"])

filegroup(
    name = "csv_random_data",
    srcs = [
        "csv_random_data.csv",
    ],
)

filegroup(
    name = "image_data",
    srcs = glob([
        "**/*.png",
    ]),
)
