package(default_visibility = [
    "//learning/adanets:__subpackages__",
    "//model_search:__subpackages__",
])

licenses(["notice"])

exports_files(["LICENSE"])

filegroup(
    name = "testdata",
    srcs = [
        "end_to_end_graph_def.pbtxt",
    ],
)
