


package(default_visibility = [
    "//visibility:public",
])

licenses(["notice"])

exports_files(["LICENSE"])

filegroup(
    name = "phoenix_configs",
    srcs = [
        "cnn_config.pbtxt",
        "dnn_config.pbtxt",
        "rnn_all_config.pbtxt",
        "rnn_last_config.pbtxt",
    ],
)
