minimum_depth: 2
maximum_depth: 21
problem_type: CNN

search_type: ADAPTIVE_COORDINATE_DESCENT

# Note: 96 convolutions is the only convolution block with batchnorm.
# This is because the 96 channel + batch norm is the stem cell in NasNet for
# Cifar benchmark
# TODO(b/172564129): Unify batchnorm
blocks_to_use: "FIXED_CHANNEL_CONVOLUTION_16"
blocks_to_use: "FIXED_CHANNEL_CONVOLUTION_32"
blocks_to_use: "FIXED_CHANNEL_CONVOLUTION_64"
blocks_to_use: "FIXED_CHANNEL_CONVOLUTION_96"  # Batch-norm
blocks_to_use: "FIXED_CHANNEL_CONVOLUTION_120"
blocks_to_use: "CONVOLUTION_3X3"
blocks_to_use: "CONVOLUTION_5X5"
blocks_to_use: "CONVOLUTION_1X3"
blocks_to_use: "CONVOLUTION_1X5"
blocks_to_use: "CONVOLUTION_1X7"
blocks_to_use: "CONVOLUTION_3X1"
blocks_to_use: "CONVOLUTION_5X1"
blocks_to_use: "CONVOLUTION_7X1"
blocks_to_use: "DOWNSAMPLE_CONVOLUTION_3X3"
blocks_to_use: "DOWNSAMPLE_CONVOLUTION_5X5"
blocks_to_use: "AVERAGE_POOL_2X2"
blocks_to_use: "AVERAGE_POOL_4X4"
blocks_to_use: "RESNET_3X3"
blocks_to_use: "RESNET_5X5"
blocks_to_use: "DUAL_RESNET"
blocks_to_use: "INCREASE_CHANNELS_3X3"
blocks_to_use: "INCREASE_CHANNELS_5X5"
blocks_to_use: "FULLY_CONNECTED"
blocks_to_use: "FULLY_CONNECTED_PYRAMID"
blocks_to_use: "MAX_POOLING_3X3"
blocks_to_use: "MAX_POOLING_5X5"
blocks_to_use: "DILATED_CONVOLUTION_2"
blocks_to_use: "DILATED_CONVOLUTION_4"
blocks_to_use: "FIXED_OUTPUT_FULLY_CONNECTED_128"
blocks_to_use: "FIXED_OUTPUT_FULLY_CONNECTED_256"
blocks_to_use: "FIXED_OUTPUT_FULLY_CONNECTED_512"
blocks_to_use: "FIXED_OUTPUT_FULLY_CONNECTED_1024"
blocks_to_use: "GENERAL_BLOCK"
blocks_to_use: "CIFAR_NASA_REDUCTION"
blocks_to_use: "CIFAR_NASA"

# Three user suggestions with the same NasNet-Cifar architecture (train this
# architecture three times with differen hparams, before starting to search).
user_suggestions {
  architecture: "FIXED_CHANNEL_CONVOLUTION_96"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA_REDUCTION"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA_REDUCTION"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
}

user_suggestions {
  architecture: "FIXED_CHANNEL_CONVOLUTION_96"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA_REDUCTION"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA_REDUCTION"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
}

user_suggestions {
  architecture: "FIXED_CHANNEL_CONVOLUTION_96"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA_REDUCTION"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA_REDUCTION"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
  architecture: "CIFAR_NASA"
}
