minimum_depth: 2
maximum_depth: 20
problem_type: CNN

search_type: ADAPTIVE_COORDINATE_DESCENT

blocks_to_use: "FIXED_CHANNEL_CONVOLUTION_16"
blocks_to_use: "FIXED_CHANNEL_CONVOLUTION_32"
blocks_to_use: "FIXED_CHANNEL_CONVOLUTION_64"
blocks_to_use: "FIXED_CHANNEL_CONVOLUTION_120"
blocks_to_use: "CONVOLUTION_3X3"
blocks_to_use: "CONVOLUTION_5X5"
blocks_to_use: "DOWNSAMPLE_CONVOLUTION_3X3"
blocks_to_use: "DOWNSAMPLE_CONVOLUTION_5X5"
blocks_to_use: "AVERAGE_POOL_2X2"
blocks_to_use: "AVERAGE_POOL_4X4"
blocks_to_use: "RESNET_3X3"
blocks_to_use: "RESNET_5X5"
blocks_to_use: "INCREASE_CHANNELS_3X3"
blocks_to_use: "INCREASE_CHANNELS_5X5"
blocks_to_use: "FULLY_CONNECTED"
blocks_to_use: "FULLY_CONNECTED_PYRAMID"
blocks_to_use: "MAX_POOLING_3X3"
blocks_to_use: "MAX_POOLING_5X5"
blocks_to_use: "DILATED_CONVOLUTION_2"
blocks_to_use: "DILATED_CONVOLUTION_4"
blocks_to_use: "FIXED_OUTPUT_FULLY_CONNECTED_128"
blocks_to_use: "FIXED_OUTPUT_FULLY_CONNECTED_256"
blocks_to_use: "FIXED_OUTPUT_FULLY_CONNECTED_512"
blocks_to_use: "FIXED_OUTPUT_FULLY_CONNECTED_1024"
blocks_to_use: "CONVOLUTION_1X3"
blocks_to_use: "CONVOLUTION_1X5"
blocks_to_use: "CONVOLUTION_1X7"
blocks_to_use: "CONVOLUTION_3X1"
blocks_to_use: "CONVOLUTION_5X1"
blocks_to_use: "CONVOLUTION_7X1"
blocks_to_use: "GENERAL_BLOCK"
blocks_to_use: "DUAL_RESNET"
blocks_to_use: "FIXED_CHANNEL_CONVOLUTION_96"

beam_size: 5
increase_complexity_probability: 0.9
use_parameter_scaled_training: true

user_suggestions {
  architecture: "FIXED_CHANNEL_CONVOLUTION_96"
  architecture: "FIXED_CHANNEL_CONVOLUTION_96"
}

learning_spec {
  apply_exponential_decay: true
  max_decay_times: 10000
}

ensemble_spec {
  combining_type: AVERAGE_ENSEMBLE
  ensemble_search_type: INTERMIXED_NONADAPTIVE_ENSEMBLE_SEARCH
  intermixed_search {
    width: 3
    try_ensembling_every: 5
    num_trials_to_consider: 15
  }
}
